#!/bin/bash

# MX Linux mx-updater-view-auto-update-dpkg-logs pkexec wrapper to retain QT environment
# Usage:
#        mx-updater-view-auto-update-dpkg-logs apps ...
# adapted from mx-pkexec by dolphin_oracle for MX-Linux
# original code by fehlix for MX-Linux

if test "$EUID" != 0; then
    # normal user
    QTENV="/tmp/mx-updater-view-auto-update-dpkg-logs-qtenv.$EUID.$PPID.$$.$RANDOM$RANDOM"
    env | grep -E '^QT_'  | sed -e 's/^/export /' 2>/dev/null  > "$QTENV"
    chmod +r "$QTENV"
    pkexec /usr/bin/mx-updater-view-auto-update-dpkg-logs "--qtenv" "$QTENV" "${@}"
    if [ -f "$QTENV" ] ; then
        rm  $QTENV
    fi
fi
if test "$EUID" == 0; then
    # root user
    if  [ "x$1" = "x--qtenv" ]; then
        QTENV="$2"
        shift
        shift
        if [ -r "$QTENV" -a  "$QTENV" != "${QTENV#/tmp/mx-updater-view-auto-update-dpkg-logs-qtenv.}" ] ; then 
            . $QTENV
            rm  $QTENV
        fi
        PATH="/usr/local/bin:$PATH"
    fi
    eval set "$@"
    RUN="$1"
    shift
    echo Starting  "$RUN" "${@}"
    command -v "$RUN" >/dev/null || { echo "mx-updater-view-auto-update-dpkg-logs: Command '$RUN' not found"; exit 1; }
    exec "$RUN" "${@}"
fi
exit

