#!/bin/bash

apt-get update

echo

#If packages pinned with Synaptic (result 0), filter pinned upgradeables out with grep -v before getting count,
#otherwise (result 1 or 2) get a count of all upgradeables. 
grep -q ^Package /var/lib/synaptic/preferences 2>/dev/null
if [ $? -eq 0 ]
  then
    Count=$(apt list --upgradable 2>/dev/null |\
            grep -v $(grep ^Package /var/lib/synaptic/preferences | awk '{print "-e ^"$2"/"}') |\
            grep "]"$ | wc -l)
  else
    Count=$(apt list --upgradable 2>/dev/null | grep "]"$ | wc -l)
fi

case $Count in
  0)  UpdatesMsg="`/usr/bin/gettext -d apt-notifier \"0 updates available\"`"
      ;;

  1)  UpdatesMsg="`/usr/bin/gettext -d apt-notifier \"1 new update available\"`"
      ;;

  *) #UpdatesMsg="`/usr/bin/gettext -d apt-notifier -s $Count \"$n new updates available\"`" # doesn't work?
      UpdatesMsg="`/usr/bin/gettext -d apt-notifier -s $Count \"Updates\"`" # so use this
      ;;
esac

echo $UpdatesMsg
echo

exit
