#!/bin/bash

# Kill any notifier(s) running
if [ "`ps ux|grep '/usr/bin/apt-notifier.py'|grep -v 'grep'`" \> "" ];
  then
  kill `ps ux|grep '/usr/bin/apt-notifier.py'|grep -v 'grep'| awk '{ print $2 }'`
fi

# create the apt-notifierrc file if it doesn't already exist
if ! [ -f ~/.kde/share/config/apt-notifierrc ]; 
then 
  echo -e '[General]\nAutoStart=true\n'> ~/.kde/share/config/apt-notifierrc
  chmod 644 ~/.kde/share/config/apt-notifierrc
fi

# start the notifier
python /usr/bin/apt-notifier.py& disown -h

exit 0