#!/bin/bash

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/mnotify-none.png /usr/share/icons/mnotify-some.png
fi
# End automatically added section


# postrm script for apt-notifier

set -e

case "$1" in
  remove)
    if [ $(grep  15periodic-update /var/lib/dpkg/info/mepis-config.list 2>/dev/null) ];
      then : ;
      else rm /etc/apt/apt.conf.d/15periodic-update;
    fi
  ;;
  *)
    :
  ;;  
esac
exit 0

